# https://docs.travis-ci.com/user/travis-lint

language: node_js

os:
  - windows
  - linux
  - osx

node_js:
  - 14
  - 12
  - 10

jobs:
  include:
    - node_js: 8
      before_script: |
        npm install postcss@7
        nvm install 10
        nvm use 10
        npm run pretest:tape
        nvm use 8
      script: npm run test:tape:7 -- --ci true

install:
  - git config --global core.autocrlf false
  - git checkout -qf ${TRAVIS_COMMIT}
  - npm install --ignore-scripts
