# https://docs.travis-ci.com/user/travis-lint

language: node_js

os:
  - windows
  - linux
  - osx

node_js:
  - 12
  - 10
  - 8

jobs:
  include:
    - node_js: 8
      after_install: npm install postcss@7
      script: npm run test:tape:7 -- --ci true

install:
  - git config --global core.autocrlf false
  - git checkout -qf ${TRAVIS_COMMIT}
  - npm install --ignore-scripts
